version: "3.8"
services:
  app:
    build: ./quiz-app-backend
    ports:
      - "3000:3000"
    volumes:
      - ./quiz-app-backend:/usr/src/app
    working_dir: /usr/src/app
    command: node server.js
